package com.alfa.click.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "IWidgetService", targetNamespace = "http://server.webservice.click.alfa.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface IWidgetService {

	/**
	 * 
	 * @return returns
	 *         com.alfa.click.webservice.server.GetWidgetsResponse.Return
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getWidgets", targetNamespace = "http://server.webservice.click.alfa.com/", className = "com.alfa.click.webservice.server.GetWidgets")
	@ResponseWrapper(localName = "getWidgetsResponse", targetNamespace = "http://server.webservice.click.alfa.com/", className = "com.alfa.click.webservice.server.GetWidgetsResponse")
	public com.alfa.click.webservice.server.GetWidgetsResponse.Return getWidgets();

}
