package com.alfa.click.webservice.server;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "WidgetServiceService", targetNamespace = "http://server.webservice.click.alfa.com/", wsdlLocation = "http://localhost:8080/WS/WidgetService?wsdl")
public class WidgetServiceService extends Service {

	private final static URL WIDGETSERVICESERVICE_WSDL_LOCATION;

	private final static WebServiceException WIDGETSERVICESERVICE_EXCEPTION;

	private final static QName WIDGETSERVICESERVICE_QNAME = new QName(
			"http://server.webservice.click.alfa.com/", "WidgetServiceService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("http://localhost:8080/WS/WidgetService?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		WIDGETSERVICESERVICE_WSDL_LOCATION = url;
		WIDGETSERVICESERVICE_EXCEPTION = e;
	}

	public WidgetServiceService() {
		super(__getWsdlLocation(), WIDGETSERVICESERVICE_QNAME);
	}

	// public WidgetServiceService(WebServiceFeature... features) {
	// super(__getWsdlLocation(), WIDGETSERVICESERVICE_QNAME, features);
	// }

	public WidgetServiceService(final URL wsdlLocation) {
		super(wsdlLocation, WIDGETSERVICESERVICE_QNAME);
	}

	// public WidgetServiceService(URL wsdlLocation, WebServiceFeature...
	// features) {
	// super(wsdlLocation, WIDGETSERVICESERVICE_QNAME, features);
	// }

	public WidgetServiceService(final URL wsdlLocation, final QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	// public WidgetServiceService(URL wsdlLocation, QName serviceName,
	// WebServiceFeature... features) {
	// super(wsdlLocation, serviceName, features);
	// }

	/**
	 * 
	 * @return returns IWidgetService
	 */
	@WebEndpoint(name = "WidgetServicePort")
	public IWidgetService getWidgetServicePort() {
		return super.getPort(new QName("http://server.webservice.click.alfa.com/",
				"WidgetServicePort"), IWidgetService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns IWidgetService
	 */
	@WebEndpoint(name = "WidgetServicePort")
	public IWidgetService getWidgetServicePort(final WebServiceFeature... features) {
		return super.getPort(new QName("http://server.webservice.click.alfa.com/",
				"WidgetServicePort"), IWidgetService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (WIDGETSERVICESERVICE_EXCEPTION != null) {
			throw WIDGETSERVICESERVICE_EXCEPTION;
		}
		return WIDGETSERVICESERVICE_WSDL_LOCATION;
	}

}
