package com.alfa.click.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebService;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService
public interface IWidgetService {

	/**
	 * 
	 * @return returns com.alfa.click.webservice.GetWidgetsResponse.Return
	 */
	@WebMethod
	Widgets getWidgets();

}